### ISSUE TITLE
Queries with a user field do not work after importing.

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_service_definition_manager#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server**
Seen on Trial, Experimental, etc?

**Additional context**
`could not resolve our linkField`

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/519c3b99896b9baa0c1b95b9a3be507d4657d3b2
