### ISSUE TITLE
Multi-tenant definition update

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_service_definition_manager#7]
> “As a sys admin, I want to update definitions for multiple tenants.”

## Requirements
1. A new route to update definitions
2. Read app.json from GitHub?
3. Update a set of tenants.

### Tasks
- [ ] Write Documentation

## Reference
No UI needed.

**Comment by Achoobert** [comment]
I'm not sure how this might effect this task: 
but I have noticed that the CARs server sometimes becomes noticablly less responsive when definitions are updated. The fix I've used is to restart the server

https://github.com/digi-serve/cars_app/issues/46
